<?php
defined('BASEPATH') OR exit('No direct script access allowed');

class ThemeMapper {
    
    protected $CI;

    public function __construct() {
        $this->CI =& get_instance();
        $this->CI->load->model('AiModel');
    }

    /**
     * Injects dynamic design tokens into the generated CSS
     * 
     * @param string $css The raw CSS generated by the TemplateGenerator
     * @param int $website_id The active website/client ID
     * @return string CSS with variables mapped
     */
    public function apply_theme($css, $website_id = 0) {
        // Fetch all tokens for this website
        $tokens = $this->CI->AiModel->get_tokens($website_id);
        
        if (empty($tokens)) {
            return $css;
        }

        // We will build a :root CSS block to inject at the top of the CSS
        $root_vars = ":root {\n";
        foreach ($tokens as $token) {
            // Ensure token key starts with -- (e.g., --ai-primary-color)
            $key = trim($token->token_key);
            if (strpos($key, '--') !== 0) {
                $key = '--' . $key;
            }
            $root_vars .= "    " . htmlspecialchars($key) . ": " . htmlspecialchars($token->token_value) . ";\n";
        }
        $root_vars .= "}\n\n";

        // Prepend the CSS variables to the actual CSS block
        return $root_vars . $css;
    }
}
